version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_lab
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: lab3Moja
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: